/**
 * The trademark disclaimer, and links to the legal pages.
 *
 * WHY THIS EXISTS: before issue #184 the disclaimer lived in exactly two places a real user never
 * looks — `app/index.html`'s `<noscript>` block, which no one with JavaScript enabled ever renders,
 * and the generated `/guide/` pages. Grepping the whole rendered SPA for "unofficial", "trademark"
 * or "Snowflake Inc" returned nothing. The product carries someone else's trademark on every screen
 * and said so on none of them.
 *
 * THE DISCLAIMER IS UNCONDITIONAL; THE LINKS ARE NOT. The disclaimer is true on every deployment,
 * so it always renders. The legal pages, by contrast, are generated only when an operator identity
 * is configured (pipeline/src/write/legalConfig.ts) — on a LAN or localhost instance they do not
 * exist. Linking to them there would not produce a 404: the SPA catch-all answers any unknown path
 * with the app shell at 200, so the reader would land silently in the application instead of a
 * policy. That is worse than no link, which is why `legalPages` is reported by /api/me rather than
 * assumed.
 *
 * `variant` exists because this appears in two very different frames — a wide page footer, and a
 * 320px settings panel — and squeezing one layout into both produced a link row that wrapped
 * badly in the panel.
 */

interface SiteFooterProps {
  /** From `/api/me`. When false, only the disclaimer renders. */
  legalPages: boolean;
  /** From `/api/me` (issue #193). Gates the support link, so an instance that cannot deliver a
   *  message never offers to take one. */
  supportAvailable?: boolean;
  /** "page" for the signed-out surfaces; "compact" for the settings panel. */
  variant?: "page" | "compact";
}

const LINKS: Array<{ href: string; label: string }> = [
  { href: "/privacy/", label: "Privacy" },
  { href: "/terms/", label: "Terms" },
  { href: "/about/", label: "About" },
  { href: "/accessibility/", label: "Accessibility" },
  { href: "/security/", label: "Security" },
];

export function SiteFooter({ legalPages, supportAvailable = false, variant = "page" }: SiteFooterProps) {
  const compact = variant === "compact";
  // Support sits first: it is the only link here someone actively needs, rather than one they are
  // sent to look up.
  const links = supportAvailable ? [{ href: "/support", label: "Contact support" }, ...LINKS] : LINKS;

  return (
    <footer
      style={{
        borderTop: compact ? "none" : "1px solid var(--hairline)",
        marginTop: compact ? 0 : 48,
        paddingTop: compact ? 0 : 24,
        color: "var(--text-dim)",
        fontSize: compact ? 11 : 12,
        lineHeight: 1.6,
      }}
    >
      {(legalPages || supportAvailable) && (
        // Issue #195: in the 320px settings panel these five wrapped into two ragged lines that read
        // as clutter. Interpuncts and a tighter gap let them sit as one quiet run of reference text
        // rather than a list of competing choices. The page variant keeps its roomier spacing.
        <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: compact ? "3px 6px" : "8px 18px", marginBottom: 10 }}>
          {(legalPages ? links : links.filter((l) => l.href === "/support")).map((link, i) => (
            // Real navigations, not client-side routes: these are static files generated by the
            // pipeline and served by express.static ahead of the SPA catch-all. Routing them
            // through the app router would hand them straight back to the catch-all.
            <span key={link.href} style={{ display: "inline-flex", alignItems: "center", gap: compact ? 6 : 18 }}>
              {/* --text-dim, NOT --hairline: hairline is a 1px-border colour (#23252a) and is
                  effectively invisible as text on --card, so the first version of this rendered
                  separators nobody could see. */}
              {compact && i > 0 && <span aria-hidden="true" style={{ color: "var(--text-dim)", opacity: 0.6 }}>·</span>}
              <a href={link.href} style={{ color: "var(--text-muted)", textDecoration: "none" }}>
                {link.label}
              </a>
            </span>
          ))}
        </div>
      )}
      <p style={{ margin: 0, maxWidth: 620 }}>
        An independent, unofficial project &mdash; not affiliated with, endorsed by, or sponsored by
        Snowflake Inc. &ldquo;Snowflake&rdquo; and &ldquo;SnowPro&rdquo; are trademarks of Snowflake
        Inc.
      </p>
    </footer>
  );
}

/**
 * The single-line form, for inside the app.
 *
 * The full footer belongs on the signed-out surfaces; in the sidebar there is room for one muted
 * line and nothing more. It carries the part that must be visible somewhere on every screen — that
 * this is unofficial — and deliberately not the link row, which would compete with navigation.
 */
export function SidebarDisclaimer() {
  return (
    <p
      style={{
        margin: "10px 12px 0",
        fontSize: 10,
        lineHeight: 1.5,
        color: "var(--text-dim)",
        opacity: 0.75,
      }}
    >
      Unofficial &mdash; not affiliated with Snowflake Inc.
    </p>
  );
}
