/**
 * The trademark disclaimer, and links to the legal pages.
 *
 * WHY THIS EXISTS: before issue #184 the disclaimer lived in exactly two places a real user never
 * looks — `app/index.html`'s `<noscript>` block, which no one with JavaScript enabled ever renders,
 * and the generated `/guide/` pages. Grepping the whole rendered SPA for "unofficial", "trademark"
 * or "Snowflake Inc" returned nothing. The product carries someone else's trademark on every screen
 * and said so on none of them.
 *
 * THE DISCLAIMER IS UNCONDITIONAL; THE LINKS ARE NOT. The disclaimer is true on every deployment,
 * so it always renders. The legal pages, by contrast, are generated only when an operator identity
 * is configured (pipeline/src/write/legalConfig.ts) — on a LAN or localhost instance they do not
 * exist. Linking to them there would not produce a 404: the SPA catch-all answers any unknown path
 * with the app shell at 200, so the reader would land silently in the application instead of a
 * policy. That is worse than no link, which is why `legalPages` is reported by /api/me rather than
 * assumed.
 *
 * `variant` exists because this appears in two very different frames — a wide page footer, and a
 * 320px settings panel — and squeezing one layout into both produced a link row that wrapped
 * badly in the panel.
 */

interface SiteFooterProps {
  /** From `/api/me`. When false, only the disclaimer renders. */
  legalPages: boolean;
  /** "page" for the signed-out surfaces; "compact" for the settings panel. */
  variant?: "page" | "compact";
}

const LINKS: Array<{ href: string; label: string }> = [
  { href: "/privacy/", label: "Privacy" },
  { href: "/terms/", label: "Terms" },
  { href: "/about/", label: "About" },
  { href: "/accessibility/", label: "Accessibility" },
  { href: "/security/", label: "Security" },
];

export function SiteFooter({ legalPages, variant = "page" }: SiteFooterProps) {
  const compact = variant === "compact";

  return (
    <footer
      style={{
        borderTop: compact ? "none" : "1px solid var(--hairline)",
        marginTop: compact ? 0 : 48,
        paddingTop: compact ? 0 : 24,
        color: "var(--text-dim)",
        fontSize: compact ? 11 : 12,
        lineHeight: 1.6,
      }}
    >
      {legalPages && (
        <div style={{ display: "flex", flexWrap: "wrap", gap: compact ? "6px 10px" : "8px 18px", marginBottom: 10 }}>
          {LINKS.map((link) => (
            // Real navigations, not client-side routes: these are static files generated by the
            // pipeline and served by express.static ahead of the SPA catch-all. Routing them
            // through the app router would hand them straight back to the catch-all.
            <a key={link.href} href={link.href} style={{ color: "var(--text-muted)", textDecoration: "none" }}>
              {link.label}
            </a>
          ))}
        </div>
      )}
      <p style={{ margin: 0, maxWidth: 620 }}>
        An independent, unofficial project &mdash; not affiliated with, endorsed by, or sponsored by
        Snowflake Inc. &ldquo;Snowflake&rdquo; and &ldquo;SnowPro&rdquo; are trademarks of Snowflake
        Inc.
      </p>
    </footer>
  );
}

/**
 * The single-line form, for inside the app.
 *
 * The full footer belongs on the signed-out surfaces; in the sidebar there is room for one muted
 * line and nothing more. It carries the part that must be visible somewhere on every screen — that
 * this is unofficial — and deliberately not the link row, which would compete with navigation.
 */
export function SidebarDisclaimer() {
  return (
    <p
      style={{
        margin: "10px 12px 0",
        fontSize: 10,
        lineHeight: 1.5,
        color: "var(--text-dim)",
        opacity: 0.75,
      }}
    >
      Unofficial &mdash; not affiliated with Snowflake Inc.
    </p>
  );
}
